### ISSUE TITLE
VS 2019: Flash error

### ISSUE THREAD

**Issue by nordteamdev** [hydrogen31/NpcEditor#1]
Error CS0246:	The type or namespace name 'AxShockwaveFlashObjects' could not be found (are you missing a using directive or an assembly reference?)	NpcEditor	D:\...\Source\NpcEditor\Form1.cs	131	Active

Line: `private void axShockwaveFlash1_FlashCall(object sender, AxShockwaveFlashObjects._IShockwaveFlashEvents_FlashCallEvent e)`

Debug/Any CPU

**Comment by hydrogen31** [comment]
I guess this issue is caused by the Flash.ocx file not being registered in the system. If registered, the COM Reference will be loaded automatically. I have two recommendations to solve this problem:

1) You can solve the problem by registering the **Flash.ocx** file. To do this, you must run the command line as an administrator and enter the following command.

`regsvr32 "D:...\Source\NpcEditor\Flash.ocx"` (type the correct path)

![image](https://github.com/hydrogen31/NpcEditor/assets/145507211/7eee905c-08f9-4722-b15c-1d4c5f7a75ab)


2) Or... You can find `AxInterop.ShockwaveFlashObjects.dll` and `Interop.ShockwaveFlashObjects.dll` files in the released application folder. You can manually add those dll files as references to the project.


I hope these methods solve your problem.
